name = "tvpage"
description = "starter theme tvpage"
min_version = 0.17

[[tvp-templates]]
name = "Captivate"
uniqueName = "captivate"
path = "layouts/captivate"
thumbnail = "http://www.webdesigndev.com/wp-content/uploads/2012/08/114.jpg"
preview = "http://preview.tvpage.com"

[[tvp-widgets]]
name = "Carousel"
uniqueName = "carousel"
path = "layouts/tvp-widgets/carousel"
thumbnail = "http://do0631budpzeh.cloudfront.net/dev/widgets/templates/preview_Carousel.png"
preview = "http://preview.tvpage.com"
settings = ['playback']

[[tvp-widgets]]
name = "Inline"
uniqueName = "inline"
path = "layouts/tvp-widgets/inline"
thumbnail = "http://do0631budpzeh.cloudfront.net/dev/widgets/templates/preview_Inline.png"
preview = "http://preview.tvpage.com"
settings = ['playback','products']

[[tvp-widgets]]
name = "PDP"
uniqueName = "pdp"
path = "layouts/tvp-widgets/pdp"
thumbnail = "http://do0631budpzeh.cloudfront.net/dev/widgets/templates/preview_PDP.png"
preview = "http://preview.tvpage.com"
settings = ['playback']

[[tvp-widgets]]
name = "Side Bar"
uniqueName = "side-bar"
path = "layouts/tvp-widgets/side-bar"
thumbnail = "http://do0631budpzeh.cloudfront.net/dev/widgets/templates/preview_SideBar.png"
preview = "http://preview.tvpage.com"
settings = ['playback']

[[tvp-widgets]]
name = "Solo"
uniqueName = "solo"
path = "layouts/tvp-widgets/solo"
thumbnail = "http://do0631budpzeh.cloudfront.net/dev/widgets/templates/preview_Solo.png"
preview = "http://preview.tvpage.com"
settings = ['playback']